name: Publish

on:
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

concurrency:
  group: "teahouse"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"
      - name: Build the site
        run: uv run --no-dev --prerelease=allow render-engine build
      - uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./output

  # Deployment job
  deploy:
    environment:
      name: kjaymiller
      url: https://kjaymiller.com
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: website
          path: ./output
      - name: Upload
        uses: teahouse-hosting/upload@trunk
        with:
          domain: kjaymiller.com
          root: ./output/
